### ISSUE TITLE
Demultiplexing error help

### ISSUE THREAD

**Issue by rspektor** [sdparekh/zUMIs#141]
Hi,
When I try to run my samples with demultiplexing on everything runs except for the demultiplexing where I get the following error (repeated):
Can't fork, trying again in 5 seconds at /workdir/rspektor/programs/zUMIs/misc/demultiplex_BC.pl line 44.

I am unsure how to proceed.

Thank you for your help!

**Comment by cziegenhain** [comment]
Hi,

This is strange. Could you provide a bit more information on your system (eg OS, version, zUMIs version)?
Just a hunch, can you change this line (158 in zUMIs-dge2.R) as follows:
https://github.com/sdparekh/zUMIs/blob/master/zUMIs-dge2.R#L158
` demux_cmd <- paste0("perl ", opt$zUMIs_directory, "/misc/demultiplex_BC.pl ",opt$out_dir," ",opt$project, " ", samtoolsexc )`

Best,
Christoph

**Comment by jeremymsimon** [comment]
FYI I had this same issue. I am testing the fix you suggest above and will update shortly

**Comment by rspektor** [comment]
Thank you; sorry for my lack of reply. I was no longer processing the relevant data shortly after I posted.

**Comment by jeremymsimon** [comment]
The above suggested edit has a syntax error (missing the BAM file as input), but does not fix the "cannot fork" error. Full log attached here.

Any suggestions?

[02_03_2020_10_27_54_173.txt](https://github.com/sdparekh/zUMIs/files/4154989/02_03_2020_10_27_54_173.txt)

**Comment by cziegenhain** [comment]
Hi,

sorry that this is not working well for you. 
The demultiplexing will need to be able to have an open file handle for each cell, could you check if `ulimit -n` is clearly larger than the number of detected barcodes in your dataset?

I am working on a new demultiplexing solution that will hopefully be both faster and more robust, so stay tuned with further updates.

**Comment by jeremymsimon** [comment]
Our `ulimit` is set to 65536, whereas the number of lines in `*kept_barcodes.txt` is 32762. Is that what you're looking for or is there a different, perhaps larger, number of barcodes that is more relevant here?

**Comment by cziegenhain** [comment]
Hey Jeremy,

thats odd it should actually work well like this.
In any case, I tried to code a faster demultiplexing script using pysam. Just pushed that to github, so if you have python3.x and pysam installed you could give that a go!

**Comment by jeremymsimon** [comment]
Okay thanks! Giving this a test right now- will provide an update here shortly

**Comment by jeremymsimon** [comment]
Hmmm okay now I'm getting lots of errors along the way:

```Your job looked like:
###################################################################################
sbatch -o /proj/jmsimon/SLURM_logs//2020/02/14/02_14_2020_14_29_31_320 -e /proj/jmsimon/SLURM_logs//2020/02/14/02_14_2020_14_29_31_320 --time=7-12 --open-mode=append -n 24 --mem 80g --wrap="bash /proj/jmsimon/bin/zUMIs_v2.6.3/zUMIs-master.sh -y test.yaml"

###################################################################################

Job <51181461> submitted to partition <general>
Job email notification enabled

Current Working Directory: /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620


The output (if any) follows:



 You provided these parameters:
 YAML file:     test.yaml
 zUMIs directory:               /proj/jmsimon/bin/zUMIs_v2.6.3
 STAR executable                /nas/longleaf/apps/star/2.5.4b/bin/Linux_x86_64/STAR
 samtools executable            samtools
 pigz executable                /nas/longleaf/apps/pigz/2.3.4/bin/pigz
 Rscript executable             /nas/longleaf/apps/r/3.5.2/bin/Rscript
 RAM limit:   50
 zUMIs version 2.6.3a 


Fri Feb 14 14:40:24 EST 2020
Filtering...
Fri Feb 14 17:05:28 EST 2020
[1] "32761 barcodes detected."
[1] "133264251 reads were assigned to barcodes that do not correspond to intact cells."
Mapping...
[1] "2020-02-14 17:07:40 EST"
[W::bam_merge_core2] No @HD tag found.
Fri Feb 14 22:23:58 EST 2020
Counting...
[1] "2020-02-14 22:24:07 EST"
[1] "112500000 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.final_annot.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S test.filtered.tagged.Aligned.out.bam           ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid56564 ...         ||
||    Features : 1078142                                                      ||
||    Meta-features : 99717                                                   ||
||    Chromosomes/contigs : 49                                                ||
||                                                                            ||
|| Process BAM file test.filtered.tagged.Aligned.out.bam...                   ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 823148102                                            ||
||    Successfully assigned alignments : 128446647 (15.6%)                    ||
||    Running time : 9.68 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Assigning reads to features (in)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S test.filtered.tagged.Aligned.out.bam.ex.fe ... ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid56564 ...         ||
||    Features : 532446                                                       ||
||    Meta-features : 58093                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file test.filtered.tagged.Aligned.out.bam.ex.featureCounts ... ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 823148102                                            ||
||    Successfully assigned alignments : 416816171 (50.6%)                    ||
||    Running time : 10.59 minutes                                            ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Extracting reads from bam file(s)..."
[1] "Hamming distance collapse in barcode chunk 1 out of 6"
[1] "Splitting data for multicore hamming distance collapse..."
[1] "Setting up multicore cluster & generating molecule mapping tables ..."
[1] "Finished multi-threaded hamming distances"
[1] "Hamming distance collapse in barcode chunk 2 out of 6"
[1] "Splitting data for multicore hamming distance collapse..."
[1] "Setting up multicore cluster & generating molecule mapping tables ..."
[1] "Finished multi-threaded hamming distances"
[1] "Hamming distance collapse in barcode chunk 3 out of 6"
[1] "Splitting data for multicore hamming distance collapse..."
[1] "Setting up multicore cluster & generating molecule mapping tables ..."
[1] "Finished multi-threaded hamming distances"
[1] "Hamming distance collapse in barcode chunk 4 out of 6"
[1] "Splitting data for multicore hamming distance collapse..."
[1] "Setting up multicore cluster & generating molecule mapping tables ..."
[1] "Finished multi-threaded hamming distances"
[1] "Hamming distance collapse in barcode chunk 5 out of 6"
[1] "Splitting data for multicore hamming distance collapse..."
[1] "Setting up multicore cluster & generating molecule mapping tables ..."
[1] "Finished multi-threaded hamming distances"
[1] "Hamming distance collapse in barcode chunk 6 out of 6"
[1] "Splitting data for multicore hamming distance collapse..."
[1] "Setting up multicore cluster & generating molecule mapping tables ..."
[1] "Finished multi-threaded hamming distances"
[1] "Demultiplexing output bam file by cell barcode..."
[1] "Using python implementation to demultiplex."
[1] "2020-02-15 01:41:11 EST"
Demultiplexing zUMIs bam file...
Traceback (most recent call last):
  File "/proj/jmsimon/bin/zUMIs_v2.6.3/misc/demultiplex_BC.py", line 58, in <module>
    main()
  File "/proj/jmsimon/bin/zUMIs_v2.6.3/misc/demultiplex_BC.py", line 54, in main
    pin = args.pin)
  File "/proj/jmsimon/bin/zUMIs_v2.6.3/misc/demultiplex_BC.py", line 16, in demultiplex_bam
    inbam = pysam.AlignmentFile(bamfile, 'rb', threads = pin)
  File "pysam/libcalignmentfile.pyx", line 728, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 764, in pysam.libcalignmentfile.AlignmentFile._open
TypeError: _open() got an unexpected keyword argument 'threads'
[1] "2020-02-15 01:41:12 EST"
[1] "Correcting UMI barcode tags..."
[E::hts_open_format] Failed to open file /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/zUMIs_output/demultiplexed/test.GGGGGGGGGGGGGGGGGGGGGGGG.demx.bam
samtools view: failed to open "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/zUMIs_output/demultiplexed/test.GGGGGGGGGGGGGGGGGGGGGGGG.demx.bam" for reading: No such file or directory
[E::hts_open_format] Failed to open file /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/zUMIs_output/demultiplexed/test.GGGGGGGGGGGGGGGGGGGGGGGG.demx.bam
samtools view: failed to open "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/zUMIs_output/demultiplexed/test.GGGGGGGGGGGGGGGGGGGGGGGG.demx.bam" for reading: No such file or directory
.
.
.
/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.merge.sh: line 1: /nas/longleaf/apps/samtools/1.9/bin/samtools: Argument list too long
[1] "Coordinate sorting final bam file..."
[E::hts_open_format] Failed to open file /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.bam
samtools sort: can't open "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.bam": No such file or directory
[E::hts_open_format] Failed to open file /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam
samtools index: failed to open "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam": No such file or directory
rm: cannot remove ‘/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.bam’: No such file or directory
[1] "Here are the detected subsampling options:"
[1] "FALSE"
[1] "Extracting reads from bam file(s)..."
[E::hts_open_format] Failed to open file /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam
samtools view: failed to open "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam" for reading: No such file or directory
[E::hts_open_format] Failed to open file /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam
samtools view: failed to open "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam" for reading: No such file or directory
[E::hts_open_format] Failed to open file /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam
samtools view: failed to open "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam" for reading: No such file or directory
[E::hts_open_format] Failed to open file /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam
samtools view: failed to open "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam" for reading: No such file or directory
[E::hts_open_format] Failed to open file /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam
samtools view: failed to open "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam" for reading: No such file or directory
[E::hts_open_format] Failed to open file /proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam
samtools view: failed to open "/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/test.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam" for reading: No such file or directory
[1] "Working on barcode chunk 1 out of 6"
[1] "Processing 198 barcodes in this chunk..."
[1] "Working on barcode chunk 2 out of 6"
[1] "Processing 518 barcodes in this chunk..."
Error in alldt[[i]][[2]] : subscript out of bounds
Calls: bindList
Execution halted
Sat Feb 15 02:46:47 EST 2020
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/zUMIs_output/expression/test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Sat Feb 15 02:46:55 EST 2020
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2020-02-15 02:46:55 EST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/proj/jmsimon/scratch/jmsimon/Test/SPLITseq/TestRun_SPLITseq_010620/test_zUMIs_v263/zUMIs_output/expression/test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Sat Feb 15 02:47:10 EST 2020
```

Let me know what other information I can provide. Looks like there may be a few things going on simultaneously here...

**Comment by cziegenhain** [comment]
Looks pretty good to me until the demultiplexing and then it breaks. The rest should all be downstream errors. 

Which version of Python and pysam do you have running?

I often work with plate-based protocols myself and haven't used this new code with 30,000 cell runs like split-seq, but a recent 10x dataset worked great for me. 

Sorry that this is being difficult, appreciate your patience!

**Comment by jeremymsimon** [comment]
Python v3.5.1
Pysam v0.14

**Comment by cziegenhain** [comment]
A little bit of googling tells me that pysam gained the multithreaded bam decompression I'm using in v0.15. Could you update and retry? I'll add the version requirement to the documentation.

**Comment by jeremymsimon** [comment]
Upgraded and testing again. Thanks!

**Comment by jeremymsimon** [comment]
Gets a little further, but then hits a few other errors around the UMI correction step. I've attached a log file here of the entire output. 

There are txt files in the `molecule_mapping` directory, but it errors about a bunch that don't exist. Then a little bit later, it looks like you'll need a different method for merging the BAMs, as the argument list becomes too long with this many cells. Not sure if `samtools merge -b` would help here or not- would need to be tested.

[zUMIs_errLog.txt](https://github.com/sdparekh/zUMIs/files/4232350/zUMIs_errLog.txt)

**Comment by cziegenhain** [comment]
Hi Jeremy,

Cool. The ones that look like 
`cat: /proj/jmsimon/scratch/jmsimon/Zylka/SPLITseq/Top1_SPLITseq_010620/test_zUMIs_v263/zUMIs_output/molecule_mapping/test.TGGCTTCAAGTACAAGCGACGAGC.txt: No such file or directory`
are more like warnings that I need to suppress (basically a cell where no hamming distance collapse needed to be performed).

I'll change the bam merging and then hopefully we'll be on the right track!

**Comment by cziegenhain** [comment]
Pushed the change directly now - hope it works for you!

**Comment by jeremymsimon** [comment]
Testing now

**Comment by jeremymsimon** [comment]
Got a bit further:

```[1] "Extracting reads from bam file(s)..."
[1] "Working on barcode chunk 1 out of 6"
[1] "Processing 198 barcodes in this chunk..."
[1] "Working on barcode chunk 2 out of 6"
[1] "Processing 518 barcodes in this chunk..."
[1] "Working on barcode chunk 3 out of 6"
[1] "Processing 972 barcodes in this chunk..."
[1] "Working on barcode chunk 4 out of 6"
[1] "Processing 2290 barcodes in this chunk..."
[1] "Working on barcode chunk 5 out of 6"
[1] "Processing 24428 barcodes in this chunk..."
[1] "Working on barcode chunk 6 out of 6"
[1] "Processing 4355 barcodes in this chunk..."
Error in (function (cl, name, valueClass)  : 
 assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE
Calls: convert2countM -> .makewide -> <Anonymous> -> <Anonymous>
Execution halted
Fri Feb 21 07:44:30 EST 2020
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
 cannot open compressed file '/proj/jmsimon/scratch/jmsimon/Zylka/SPLITseq/Top1_SPLITseq_010620/test_zUMIs_v270a/zUMIs_output/expression/test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Fri Feb 21 07:45:07 EST 2020
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2020-02-21 07:45:07 EST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
 cannot open compressed file '/proj/jmsimon/scratch/jmsimon/Zylka/SPLITseq/Top1_SPLITseq_010620/test_zUMIs_v270a/zUMIs_output/expression/test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Fri Feb 21 07:45:36 EST 2020
/proj/jmsimon/bin/zUMIs_v2.7.0a/zUMIs-master.sh: line 310: [: =: unary operator expected```

**Comment by jeremymsimon** [comment]
@cziegenhain any update on this?

**Comment by cziegenhain** [comment]
Hi Jeremy,

Im sorry for the radio silence. Currently I'm out of office and won't get to this immediately. Since the code generally works for my test, there is probably some issue that gets triggered in your dataset but not my test cases. Do you think it's possible at all for you to share the data with me? Also does the same error occur when you sample eg 10% of the reads?

Best
Christoph

**Comment by jeremymsimon** [comment]
I am happy to share one pair of FASTQs, but it's about 100GB total. Do you have a large dropbox or similar way to share data that large?

**Comment by cziegenhain** [comment]
Closing here - we traced the issue to an unexpected value set in the downsampling field of the YAML file. zUMIs was updated to be more robust to unexpected values.
